### ISSUE TITLE
node-typescript-compiler: Error: spawn D:\Repositories\_project X\node_modules\typescript\bin\tsc ENOENT

### ISSUE THREAD

**Issue by Marvin-Brouwer** [Offirmo/offirmo-monorepo#2]
Hi,

I'm trying out this library for one of my private projects and I get the following error:
```
ts-node ./src/_compiler/bin/Compile.ts
Error: Spawn : got err event : Error: spawn D:\Repositories\_project X\node_modules\typescript\bin\tsc ENOENT
    at fail (D:\Repositories\_project X\node_modules\node-typescript-compiler\src\compile.js:61:18)
    at ChildProcess.<anonymous> (D:\Repositories\_project X\node_modules\node-typescript-compiler\src\compile.js:71:6)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  stdout: '',
  stderr: ''
}
```
I read a tsConfig file in because I need it for some other things so I just pass that and run the following command:
```typescript
    .then(async (config) => {
        const result = await tsc
            .compile(config.tsConfig)
            .catch((err) => { throw err })
        console.log('RESULT', result)
        return config
    })
```
I double checked and `D:\Repositories\_project X\node_modules\typescript\bin\tsc` does exists.
I tried compiling the project from the command line and just running `node` instead of `ts-node` and that generates the same error.
Could you maybe enhance the error logging to say what it was trying to do when the error occurred?

**Comment by Offirmo** [comment]
Hi, could I see the whole usage?
In the meantime, I'll have a look at improving error messages.

**Comment by Offirmo** [comment]
There is a "verbose" option: `.compile(config.tsConfig, [], { verbose: true })`

**Comment by Offirmo** [comment]
I published a 2.1.1 version with greatly enhanced error messages, also documenting the "verbose" option.

**Comment by Offirmo** [comment]
@Marvin-Brouwer did it solve your problem? I'm closing the issue, feel free to reopen/comment if needed.

**Comment by Marvin-Brouwer** [comment]
Sorry for not getting back to you, I moved to ttypescript for some other reasons.
I did have a similar issue there as well so I was definitely doing something wrong.
However from the looks of it the error handling has improved greatly!
I'll definitely try this library again once I have another pure Typescript project.
