### ISSUE TITLE
node-typescript-compiler: Spawn: got event "close" with error code "-4058" & signal "null"

### ISSUE THREAD

**Issue by jonnytest1** [Offirmo/offirmo-monorepo#4]
[node-typescript-compiler] Failure during tsc invocation: "Spawn: got event "err""
Error: spawn [...]\node_modules\typescript\bin\tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn [...]\\node_modules\\typescript\\bin\\tsc',
  path: '[...]\\node_modules\\typescript\\bin\\tsc',
  spawnargs: [
    '--module',
    'commonjs',
    '--moduleResolution',
    'node',
    '--target',
    'es6',
    '--typeRoots',
    'node_modules/@types',
    '--experimentalDecorators',
    '--lib',
    'dom,es6',
    '[...]\\transform.ts'
  ],
  stdout: '',
  stderr: '',
  reason: 'Spawn: got event "err"'
}

in verbose mode
both tsc and transform point to valid files

**Comment by jonnytest1** [comment]
it may be an issue with running on windows where the files are on a different disk oO

**Comment by Offirmo** [comment]
Hi @jonnytest1 thanks for the report and for trying to contribute!

I'll look into that ASAP.

**Comment by Offirmo** [comment]
Hi mate,

I tried to git clone from scratch and it worked for me, but indeed my machine is a Unix (macOS)

**First**, did you properly follow the installation instructions from [CONTRIBUTING/README.md](https://github.com/Offirmo/offirmo-monorepo/blob/master/CONTRIBUTING/README.md) ?

**Then** could you share what command you were running when you encountered the above error and in which folder?

Thanks.

**Comment by jonnytest1** [comment]
> Hi mate,
> 
> I tried to git clone from scratch and it worked for me, but indeed my machine is a Unix (macOS)
> 
> **First**, did you properly follow the installation instructions from [CONTRIBUTING/README.md](https://github.com/Offirmo/offirmo-monorepo/blob/master/CONTRIBUTING/README.md) ?
> 
> **Then** could you share what command you were running when you encountered the above error and in which folder?
> 
> Thanks.

It didn't really matter what kind of command I ran (nothing really gave me a typescript output) the folders were D:\\...\project\node_modules\typscript\bin\tsc D:\\...\example.ts

I tried the same command in a cmd directly in the d: partition and it worked(i.e. got tsc output) 

Im not too familiar with the node spawn command so im sorry if I can't help further

**Comment by Offirmo** [comment]
OK I get it! You're trying to use the "node-typescript-compiler" module!

This is a monorepo containing dozens of such modules, I wasn't understanding what you were talking about.

To troubleshoot what is not working, there is a "verbose" option: `.compile(config.tsConfig, [], { verbose: true })`

Please activate it and paste the output.

**Comment by jonnytest1** [comment]
Error: [node-typescript-compiler] Spawn: got event "close" with error code "-4058" & signal "null"
    at fail (D:\Jonathan\Projects\node\homeautomation\server\node_modules\node-typescript-compiler\src\compile.js:50:17)
    at ChildProcess.<anonymous> (D:\Jonathan\Projects\node\homeautomation\server\node_modules\node-typescript-compiler\src\compile.js:110:8)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:120:14) {
  stdout: '',
  stderr: '',
  reason: 'Spawn: got event "close" with error code "-4058" & signal "null"'
}

^^ lol i had the verbose option on already and just came to github solely to add the log output

**Comment by jonnytest1** [comment]
seems like it is known already https://github.com/Offirmo/node-typescript-compiler/issues/4

**Comment by jonnytest1** [comment]
in compile .js 
```
:spawn_params.unshift("...\\node_modules\\typescript\\lib\\tsc.js")
spawn('node', spawn_params, spawn_options)
```
helped (i also set cwd in spawn_options but i think thats irrelevant)

**Comment by KenEucker** [comment]
I am getting the same error:

```
(node:24320) UnhandledPromiseRejectionWarning: Error: [node-typescript-compiler] Spawn: got event "exit" with error code "1" & signal "null"!
    at fail (/.../node_modules/node-typescript-compiler/src/compile.js:49:17)
    at ChildProcess.<anonymous> (/.../node_modules/node-typescript-compiler/src/compile.js:103:8)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by KenEucker** [comment]
@Offirmo I've also tried running the command that n-t-c echo's out with the same result. It looks like tsc is providing the help documentation so I feel as though there's something missing in my configuration that is causing this. Here are my compilterOptions:

```
"compilerOptions": {
        "module": "commonjs",
        "target": "es5",
		"rootDir": "src",
        "outDir": "public",
        "noImplicitAny": true,
        "moduleResolution": "node",
		"sourceMap": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true
    }
```

Is there some config value I'm missing?

**Comment by Offirmo** [comment]
@KenEucker Hi,

It seems your problem doesn't come from my tool.

I'd recommend:

1. use a `tsconfig.json` file instead of writing the tsc parameters by hand in your script
1. have it working by normally calling `tsc` before automating things with a script

If you still need help, please open a dedicated ticket.

**Comment by Offirmo** [comment]
Mates, I pushed a new version with trivial error handling improvements. Most likely won't solve your problems.

May I confirm your OS? Are you all using Windows?

**Comment by KenEucker** [comment]
I'm on OS X, however, I've moved on from the implementation I was going with that used your code, unfortunately, so I can't offer testing feedback of your new version.

**Comment by Offirmo** [comment]
I'm closing this issue, anyone feel free to create a new one.
